
import React from 'react';
import { AssetCategory, InvestorProfile, AccountPurpose, Language, RiskLevel, CustomAllocation } from './types';
import {
  Wallet,
  TrendingUp,
  Layers,
  ShieldCheck,
  PieChart,
  Bitcoin,
  Home,
  MoreHorizontal,
  Coins,
  Lock,
  Copy,
  Upload,
  Share2,
  FileText,
  Download,
  ExternalLink,
  Zap,
  DollarSign,
  Plus
} from 'lucide-react';

export const RISK_MAPPING: Record<AssetCategory, RiskLevel> = {
  [AssetCategory.CASH]: RiskLevel.LOW,
  [AssetCategory.FIXED_DEPOSIT]: RiskLevel.LOW,
  [AssetCategory.BONDS]: RiskLevel.LOW,
  [AssetCategory.ETF]: RiskLevel.MEDIUM,
  [AssetCategory.MUTUAL_FUNDS]: RiskLevel.MEDIUM,
  [AssetCategory.GOLD]: RiskLevel.MEDIUM,
  [AssetCategory.REAL_ESTATE]: RiskLevel.MEDIUM,
  [AssetCategory.STOCKS]: RiskLevel.HIGH,
  [AssetCategory.CRYPTO]: RiskLevel.HIGH,
  [AssetCategory.OTHER]: RiskLevel.HIGH,
};

export const PROFILE_BENCHMARKS: Record<InvestorProfile, CustomAllocation> = {
  [InvestorProfile.CONSERVATIVE]: { lowRisk: 70, medRisk: 20, highRisk: 10 },
  [InvestorProfile.MODERATE]: { lowRisk: 40, medRisk: 40, highRisk: 20 },
  [InvestorProfile.AGGRESSIVE]: { lowRisk: 20, medRisk: 30, highRisk: 50 },
};

export const TAIWAN_BANKS = [
  { code: '004', name: '臺灣銀行 (Bank of Taiwan)' },
  { code: '005', name: '土地銀行 (Land Bank of Taiwan)' },
  { code: '006', name: '合作金庫 (Taiwan Cooperative Bank)' },
  { code: '007', name: '第一銀行 (First Bank)' },
  { code: '008', name: '華南銀行 (Hua Nan Bank)' },
  { code: '009', name: '彰化銀行 (Chang Hwa Bank)' },
  { code: '011', name: '上海銀行 (Shanghai Commercial Bank)' },
  { code: '012', name: '台北富邦 (Taipei Fubon Bank)' },
  { code: '013', name: '國泰世華 (Cathay United Bank)' },
  { code: '017', name: '兆豐銀行 (Mega Bank)' },
  { code: '021', name: '花旗銀行 (Citibank)' },
  { code: '048', name: '王道銀行 (O-Bank)' },
  { code: '050', name: '星展銀行 (DBS Bank)' },
  { code: '052', name: '渣打銀行 (Standard Chartered)' },
  { code: '053', name: '台中銀行 (Taichung Bank)' },
  { code: '081', name: '匯豐銀行 (HSBC)' },
  { code: '103', name: '臺灣新光銀行 (Shin Kong Bank)' },
  { code: '700', name: '中華郵政 (Chunghwa Post)' },
  { code: '803', name: '聯邦銀行 (Union Bank of Taiwan)' },
  { code: '805', name: '遠東銀行 (Far Eastern Bank)' },
  { code: '806', name: '元大銀行 (Yuanta Bank)' },
  { code: '807', name: '永豐銀行 (Bank SinoPac)' },
  { code: '808', name: '玉山銀行 (E.SUN Bank)' },
  { code: '812', name: '台新銀行 (Taishin Bank)' },
  { code: '822', name: '中國信託 (CTBC Bank)' },
  { code: '999', name: '其他 / 自定義 (Other / Custom)' }
];

export const TRANSLATIONS: Record<Language, any> = {
  [Language.ZH]: {
    title: 'WealthVision',
    subtitle: '年度資產分析',
    tagline: '分析您的資產配置，佈局更穩定的未來',
    description: '這是一個專業的年度對帳單整理工具。透過即時聯網與數據分析，幫助您了解跨機構的資產分佈狀況。',
    step1: '1. 設定投資目標',
    modeCategorical: '選擇投資性格',
    modeCustom: '自定義配置比例',
    enableAI: '啟動 AI 深度分析與聯網預測',
    lowRisk: '低風險',
    medRisk: '中風險',
    highRisk: '高風險',
    allocationTotal: '總計比例',
    step2: '2. 填入資產明細',
    addEntry: '新增帳目',
    duplicate: '複製',
    importExcel: '導入上期 Excel',
    bank: '銀行名稱/代碼',
    purpose: '戶頭用途',
    category: '資產類別',
    amount: '餘額',
    notes: '備註',
    analyze: '開始產出分析報表',
    analyzing: '正在計算資產配置數據...',
    reportTitle: '年度資產分析報告',
    totalWealth: '資產總淨值',
    currentDistribution: '目前的資產分佈圖',
    riskAssessment: 'AI 深度風險評估',
    rebalanceAdvice: 'AI 資產再平衡建議',
    suggestedAllocation: 'AI 建議分配比例 (%)',
    marketOutlook: 'AI 市場展望 (2026+)',
    deltaTitle: '配置偏移分析 (實際 vs 目標)',
    deltaSurplus: '超出預期',
    deltaDeficit: '低於預期',
    actual: '實際',
    target: '目標',
    editData: '修改資料',
    backToReport: '返回現有報告',
    downloadReport: '下載 Excel 報表',
    downloadPdf: '產出 PDF 報告',
    shareLink: '分享分析結果 (連結)',
    export: '匯出 / 分享',
    customBankPlaceholder: '輸入銀行名稱',
    currency: '報告幣別',
    simulationMode: '試算模式',
    simulationDesc: '固定總淨值，調整單一資產時剩餘資金將轉入自由資金池。',
    freeCash: '剩餘可分配資金 (自由資金)',
    simulating: '模擬試算中...',
    deltaDetails: '偏離詳情',
    simEditorTitle: '數值試算編輯器',
    addSimAsset: '添加試算標的',
    resetSim: '重設試算變動',
    riskLegend: '標的風險說明',
    profiles: {
      [InvestorProfile.CONSERVATIVE]: '保守型',
      [InvestorProfile.MODERATE]: '穩健型',
      [InvestorProfile.AGGRESSIVE]: '冒險型'
    },
    profileDesc: {
      [InvestorProfile.CONSERVATIVE]: '偏好低風險與穩定的回報 (低70/中20/高10)',
      [InvestorProfile.MODERATE]: '在風險與回報間平衡 (低40/中40/高20)',
      [InvestorProfile.AGGRESSIVE]: '追求高成長與高波動 (低20/中30/高50)'
    },
    purposes: {
      [AccountPurpose.SAVINGS]: '一般存款',
      [AccountPurpose.BROKERAGE]: '證券/投資',
      [AccountPurpose.GOLD]: '黃金存摺',
      [AccountPurpose.FOREIGN_CURRENCY]: '外幣戶',
      [AccountPurpose.FIXED_DEPOSIT]: '定存',
      [AccountPurpose.OTHER]: '其他'
    },
    categories: {
      [AssetCategory.CASH]: '現金/活存',
      [AssetCategory.STOCKS]: '個別股票',
      [AssetCategory.ETF]: 'ETF/指數基金',
      [AssetCategory.BONDS]: '債券/固定收益',
      [AssetCategory.MUTUAL_FUNDS]: '共同基金',
      [AssetCategory.CRYPTO]: '加密貨幣',
      [AssetCategory.REAL_ESTATE]: '房地產',
      [AssetCategory.GOLD]: '黃金資產',
      [AssetCategory.FIXED_DEPOSIT]: '定期存款',
      [AssetCategory.OTHER]: '其他'
    }
  },
  [Language.EN]: {
    title: 'WealthVision',
    subtitle: 'Yearly Asset Analysis',
    tagline: 'Analyze your wealth, secure your future.',
    description: 'A professional yearly consolidation tool. Understand your asset distribution with real-time insights.',
    step1: '1. Set Investment Goals',
    modeCategorical: 'Select Profile',
    modeCustom: 'Custom Allocation (%)',
    enableAI: 'Enable AI Deep Analysis & Market Search',
    lowRisk: 'Low Risk',
    medRisk: 'Medium Risk',
    highRisk: 'High Risk',
    allocationTotal: 'Total',
    step2: '2. Asset Details',
    addEntry: 'Add Entry',
    duplicate: 'Duplicate',
    importExcel: 'Import Previous Excel',
    bank: 'Bank Name/Code',
    purpose: 'Account Purpose',
    category: 'Asset Class',
    amount: 'Balance',
    notes: 'Notes',
    analyze: 'Generate Analysis Report',
    analyzing: 'Calculating portfolio data...',
    reportTitle: 'Yearly Analysis Report',
    totalWealth: 'Total Net Worth',
    currentDistribution: 'Asset Distribution',
    riskAssessment: 'AI Risk Assessment',
    rebalanceAdvice: 'AI Rebalancing Advice',
    suggestedAllocation: 'AI Suggested Allocation (%)',
    marketOutlook: 'AI Market Outlook',
    deltaTitle: 'Allocation Offset Analysis',
    deltaSurplus: 'Surplus',
    deltaDeficit: 'Deficit',
    actual: 'Actual',
    target: 'Target',
    editData: 'Edit Data',
    backToReport: 'Back to Report',
    downloadReport: 'Excel Report',
    downloadPdf: 'PDF Report',
    shareLink: 'Share via Link',
    export: 'Export / Share',
    customBankPlaceholder: 'Enter bank name',
    currency: 'Currency',
    simulationMode: 'Simulate',
    simulationDesc: 'Fixed total wealth. Adjustments affect the free funds pool.',
    freeCash: 'Remaining Unallocated (Free Funds)',
    simulating: 'Simulating...',
    deltaDetails: 'Offset Details',
    simEditorTitle: 'Simulation Value Editor',
    addSimAsset: 'Add Test Asset',
    resetSim: 'Reset Simulation',
    riskLegend: 'Risk Classification Legend',
    profiles: {
      [InvestorProfile.CONSERVATIVE]: 'Conservative',
      [InvestorProfile.MODERATE]: 'Moderate',
      [InvestorProfile.AGGRESSIVE]: 'Aggressive'
    },
    profileDesc: {
      [InvestorProfile.CONSERVATIVE]: 'Capital preservation (70/20/10)',
      [InvestorProfile.MODERATE]: 'Balanced risk (40/40/20)',
      [InvestorProfile.AGGRESSIVE]: 'High growth (20/30/50)'
    },
    purposes: {
      [AccountPurpose.SAVINGS]: 'Savings',
      [AccountPurpose.BROKERAGE]: 'Brokerage',
      [AccountPurpose.GOLD]: 'Gold Account',
      [AccountPurpose.FOREIGN_CURRENCY]: 'Foreign Currency',
      [AccountPurpose.FIXED_DEPOSIT]: 'Fixed Deposit',
      [AccountPurpose.OTHER]: 'Other'
    },
    categories: {
      [AssetCategory.CASH]: 'Cash/Savings',
      [AssetCategory.STOCKS]: 'Individual Stocks',
      [AssetCategory.ETF]: 'ETFs/Index Funds',
      [AssetCategory.BONDS]: 'Bonds/Fixed Income',
      [AssetCategory.MUTUAL_FUNDS]: 'Mutual Funds',
      [AssetCategory.CRYPTO]: 'Cryptocurrency',
      [AssetCategory.REAL_ESTATE]: 'Real Estate',
      [AssetCategory.GOLD]: 'Gold Assets',
      [AssetCategory.FIXED_DEPOSIT]: 'Fixed Deposit',
      [AssetCategory.OTHER]: 'Other'
    }
  }
};

export const ASSET_ICONS: Record<AssetCategory, React.ReactNode> = {
  [AssetCategory.CASH]: <Wallet className="w-5 h-5" />,
  [AssetCategory.STOCKS]: <TrendingUp className="w-5 h-5" />,
  [AssetCategory.ETF]: <Layers className="w-5 h-5" />,
  [AssetCategory.BONDS]: <ShieldCheck className="w-5 h-5" />,
  [AssetCategory.MUTUAL_FUNDS]: <PieChart className="w-5 h-5" />,
  [AssetCategory.CRYPTO]: <Bitcoin className="w-5 h-5" />,
  [AssetCategory.REAL_ESTATE]: <Home className="w-5 h-5" />,
  [AssetCategory.GOLD]: <Coins className="w-5 h-5" />,
  [AssetCategory.FIXED_DEPOSIT]: <Lock className="w-5 h-5" />,
  [AssetCategory.OTHER]: <MoreHorizontal className="w-5 h-5" />
};

export const COLORS = ['#2563eb', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6', '#ec4899', '#06b6d4', '#64748b'];
